apiVersion: v1
kind: Secret
metadata:
 name: mysql-secrets
 namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "MTIzNA==" #1234
  MYSQL_USER: "YXBwX3VzZXI=" #app_user
  MYSQL_PASSWORD: "MTIzNA==" #1234

